In [227]:
import numpy as np

In [228]:
A = np.random.randint(1,10,size = (3,3))
B = np.random.randint(1,10,size = (3,2))

In [229]:
A

array([[7, 1, 2],
       [6, 5, 5],
       [9, 6, 3]])

In [230]:
B

array([[7, 5],
       [1, 2],
       [2, 7]])

In [231]:
c = A@B
c

array([[54, 51],
       [57, 75],
       [75, 78]])

In [232]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [233]:
A = np.random.randint(1,10,size = (3,3))
B = np.random.randint(1,10,size = (3,2))

np.dot(A,B)

array([[77, 79],
       [59, 70],
       [58, 74]])

In [234]:
c = np.array(a)@np.array(b)
c

array([[4, 1],
       [2, 2]])

In [235]:
a = np.array([[1,1,1], [1,2,3]])
b = np.array([[1, 1], [1, 2], [1, 3]])

result = a@b
result

array([[ 3,  6],
       [ 6, 14]])

In [236]:
a = np.array([[1, 1, 1], [1, 2, 3]])
b = np.array([[1], [3], [2]])

result = a@b
result


array([[ 6],
       [13]])

In [237]:
a = np.array([[3, 6], [6, 14]])
b = np.array([[1], [.5]])

result = a@b
result


array([[ 6.],
       [13.]])

In [238]:
a = (3 * 1) + (6 * .5)
b = (6 * 1) + (14 * .5)

print(a)
print(b)

6.0
13.0
